# Generated by Django 5.1.3 on 2025-04-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='shared_with',
        ),
    ]
