# Generated by Django 5.1.3 on 2025-01-10 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['-rating', 'name'], 'verbose_name_plural': 'Colleges'},
        ),
        migrations.RemoveField(
            model_name='college',
            name='contact',
        ),
        migrations.AddField(
            model_name='college',
            name='accreditation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='contact_primary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='contact_secondary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='courses_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='institution_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('community', 'Community')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='college',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='notable_alumni',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='college',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='college',
            name='scholarships_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='college',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='student_teacher_ratio',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='total_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='virtual_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['slug'], name='api_college_slug_07a081_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['is_featured'], name='api_college_is_feat_6abe1f_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['rating'], name='api_college_rating_2e7987_idx'),
        ),
    ]
