# Generated by Django 5.1.3 on 2025-04-02 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop'), ('COMPETITION', 'Competition'), ('WEBINAR', 'Webinar')], max_length=50)),
                ('description', models.TextField()),
                ('speaker', models.CharField(blank=True, max_length=255, null=True)),
                ('registration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('contact_primary', models.CharField(blank=True, default='', max_length=100)),
                ('contact_secondary', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True)),
                ('affiliation', models.CharField(max_length=255)),
                ('accreditation', models.CharField(blank=True, default='', max_length=255)),
                ('institution_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('community', 'Community')], default='private', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('student_teacher_ratio', models.CharField(blank=True, default='', max_length=20)),
                ('placement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('courses_offered', models.JSONField(blank=True, default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('logo', models.URLField(blank=True)),
                ('image', models.URLField()),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, default='')),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('notable_alumni', models.JSONField(blank=True, default=list)),
                ('scholarships_available', models.BooleanField(default=False)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Colleges',
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['slug'], name='resources_c_slug_6b7264_idx'), models.Index(fields=['is_featured'], name='resources_c_is_feat_8aeaa5_idx'), models.Index(fields=['rating'], name='resources_c_rating_371694_idx')],
            },
        ),
    ]
