# Generated by Django 5.1.3 on 2025-04-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_radar', '0002_alter_resource_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='resource',
            name='_favicon_url',
            field=models.URLField(blank=True, db_column='favicon_url', null=True),
        ),
    ]
