# Generated by Django 5.1.3 on 2025-04-02 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='subjects.program'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'program', 'semester')},
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['year', 'semester'], name='subjects_qu_year_e25a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['status'], name='subjects_qu_status_809635_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionpaper',
            unique_together={('subject', 'year', 'semester')},
        ),
    ]
