# Generated by Django 5.1.3 on 2025-04-02 13:27

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Program = apps.get_model('subjects', 'Program')
    Subject = apps.get_model('subjects', 'Subject')
    User = apps.get_model('users', 'User')

    # Create BCA program
    bca = Program.objects.create(
        name='BCA',
        description='Bachelor of Computer Applications',
        duration_years=4,
        is_active=True
    )

    # Get admin user
    admin = User.objects.get(username='admin')

    # Create subjects for first semester
    subjects_data = [
        {'code': 'CSC101', 'name': 'Introduction to Programming', 'semester': 1},
        {'code': 'CSC102', 'name': 'Digital Logic', 'semester': 1},
        {'code': 'CSC103', 'name': 'Computer Architecture', 'semester': 1},
        {'code': 'CSC104', 'name': 'Mathematics I', 'semester': 1},
        {'code': 'CSC105', 'name': 'English I', 'semester': 1},
    ]

    for subject_data in subjects_data:
        Subject.objects.create(
            program=bca,
            **subject_data
        )

def reverse_initial_data(apps, schema_editor):
    Program = apps.get_model('subjects', 'Program')
    Program.objects.filter(name='BCA').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('subjects', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
