# Generated by Django 5.1.3 on 2025-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
