# Generated by Django 5.1.3 on 2025-05-04 14:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload PDF files only', upload_to='syllabus/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('version', models.CharField(help_text='Syllabus version (e.g., "2023v1")', max_length=20)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current active syllabus')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this syllabus is available for viewing')),
                ('description', models.TextField(blank=True, help_text='Additional notes or summary about this syllabus version')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(help_text='The subject this syllabus is for', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='question_papers.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_syllabi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'ordering': ['subject__program', 'subject__semester', 'version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('subject',), name='unique_current_syllabus_per_subject')],
            },
        ),
    ]
