# Generated by Django 5.1.3 on 2025-04-29 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(default='Nepal', max_length=255)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('primary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('tertiary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('programs', models.JSONField(default=list)),
                ('facilities', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('admission_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMING_SOON', 'Coming Soon')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/')),
                ('logo_url', models.URLField(blank=True, default='')),
                ('extracted_favicon', models.URLField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='college_covers/')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('views_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_colleges', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_colleges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollegeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='colleges.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_colleges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College Favorite',
                'verbose_name_plural': 'College Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('college', 'user')},
            },
        ),
    ]
