# Generated by Django 5.1.3 on 2025-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='views_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
