# Generated by Django 5.1.3 on 2025-05-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_college_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='facilities',
            field=models.JSONField(default=list, help_text='List of facilities available at the college'),
        ),
        migrations.AlterField(
            model_name='college',
            name='programs',
            field=models.JSONField(default=list, help_text='List of programs offered by the college'),
        ),
    ]
