# Generated by Django 5.1.3 on 2025-04-09 10:46

import api.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, formats: jpg, jpeg, png, gif)', null=True, upload_to=api.apps.users.models.profile_picture_path, validators=[api.apps.users.models.validate_image_file]),
        ),
    ]
